### ISSUE TITLE
Java 2013-003 and 10.6 Update 15 broke vanilla catalogs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#119]
```
InstaUp2Date chokes on current catalogs due to Apple removing old Java updates. 
Patch attached.

Finding and validating the sources for 10.8_vanilla
    iTunes 11.0.2 - found based on checksum and verified in less than one second Megabytes/sec)
    Java for OS X 2013-002 - looking based on display nameTraceback (most recent call last):ond
 File "instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 716, in <module>
   main()
 File "instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 671, in main
   thisController.findItems()
 File "instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 330, in findItems
   thisItem.findItem(progressReporter=progressReporter)
 File "/Users/Lits/instadmg/AddOns/InstaUp2Date/Resources/installerPackage.py", line 158, in findItem
   self.filePath = cacheController.findItem(self.source, self.checksumType, self.checksumValue, self.displayName, additionalSourceFolders, progressReporter)
 File "/Users/Lits/instadmg/AddOns/InstaUp2Date/Resources/cacheController.py", line 307, in findItem
   raise Exception('Got status code: %s while trying to connect to remote url: %s' % (str(error.code), nameOrLocation))
Exception: Got status code: 404 while trying to connect to remote url: 
http://support.apple.com/downloads/DL1572/en_US/JavaForOSX2013-002.dmg

```

Original issue reported on code.google.com by `MagerV...@gmail.com` on 19 Apr 2013 at 8:15

Attachments:
- [java20130419.patch](https://storage.googleapis.com/google-code-attachments/instadmg/issue-119/comment-0/java20130419.patch)

**Comment by GoogleCodeExporter** [comment]
```
Catalog files are generally updated 7 days after the release of updates. In 
this case, an update should be available some time after 2013-04-23.
```

Original comment by `n8felton` on 19 Apr 2013 at 2:36

**Comment by GoogleCodeExporter** [comment]
```
Yes, but in this case Apple broke the current catalogs by removing the old java 
updates. New users who try to setup InstaDMG are greeted with a python 
traceback.

```

Original comment by `MagerV...@gmail.com` on 19 Apr 2013 at 2:42

**Comment by GoogleCodeExporter** [comment]
```
I'm on it, thanks for the report.
```

Original comment by `a...@aru-b.com` on 19 Apr 2013 at 9:44
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
@Allister

Why do we include the java updates for 10.7 and 10.8? I know that we included 
Java updates for 10.6 because Java was included with the OS, but 10.7 and 10.8 
it is now an optional install. If we hold the vanilla catalogs to ONLY be the 
updates that are needed after a base install, then Java should not be included 
in the vanilla catalog files for 10.7 and 10.8.
```

Original comment by `n8felton` on 22 Apr 2013 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
Good point, and it'll save everyone a ton of trouble the next time java updates 
break (which is probably like next week).
```

Original comment by `MagerV...@gmail.com` on 22 Apr 2013 at 5:07

**Comment by GoogleCodeExporter** [comment]
```
CrashPlan. I don't think Java is as easy to ignore as Flash, and I hope the 
containment Safari has implemented will make the churn on that topic reduced in 
the near future. Wishful thinking/masochistic, but until that pretty-critical 
product(CrashPlan) doesn't require it I'm inclined to include it. 

```

Original comment by `a...@aru-b.com` on 22 Apr 2013 at 9:15

**Comment by GoogleCodeExporter** [comment]
```
So add Java to a separate catalog, just like the printer drivers.
```

Original comment by `MagerV...@gmail.com` on 23 Apr 2013 at 5:46

**Comment by GoogleCodeExporter** [comment]
```
I've been wanting to create a "plugins.catalog" for a while now, however, as 
@gneagle pointed out in the IRC channel, none of the plugins are really 
InstaDMG friendly as they are not deployable out of the box. The Java installer 
from Oracle's website does not currently work with InstaDMG, Flash and Reader 
also do not work. For now the only one we would be able to include would in 
fact be this Java update from Apple.

Thoughts?
```

Original comment by `n8felton` on 23 Apr 2013 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
Please, let's try to solve the big picture problems later and concentrate on 
getting the vanilla catalogs to work. Either A) accept my patch above which 
restores them to working order with minimal changes, or B) delete Java 6 from 
the vanilla images. Sites that still want to include Apple's Java 6 in the base 
image can simply add it to their local catalog files.
```

Original comment by `MagerV...@gmail.com` on 23 Apr 2013 at 3:04

**Comment by GoogleCodeExporter** [comment]
```
Agreed, for now I am in favor of accepting the patch as is and making changes 
later. MagerValp makes a good point that anyone new to InstaDMG, or users who 
rely on syncing their catalog files with the svn repo, are currently unable to 
use the r473 catalog files.

My hashes match the ones of this patch. I recommend this patch be applied ASAP. 
As I have been requested not to make changes to the core OS catalog files, we 
will need Allister to accept this patch.
```

Original comment by `n8felton` on 23 Apr 2013 at 9:34

**Comment by GoogleCodeExporter** [comment]
```
Fixed in Rev r474
```

Original comment by `n8felton` on 26 Apr 2013 at 12:47
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
Still same problem for me in rev 479.
```

Original comment by `v.bjorkd...@gmail.com` on 25 Jun 2013 at 2:22
