### ISSUE TITLE
instaUpToDate included download error?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#33]
```
Sorry, will fill in the rest tomorrow.....
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?
Checksumming Safari4.0.4SnowLeopard.dmg (30022787 bytes) in chunks of 5242880 
bytes: 0%  
17%  34%  52%  69%  87%  100%
File:   Safari 4.0.4 for SnowLeopard 
    Status:             Verified 
    Source:             Downloaded from Archive 
    Archive:
        Type:           dmg
        Location:       
http://appldnld.apple.com.edgesuite.net/content.info.apple.com/Safari4/061-
7514.20091116.VgrPf/Safari4.0.4SnowLeopard.dmg
        Checksum:       fb1755e32e9019e929474ef97ba4da219dee8b8f
        Checksum Type:      sha1
        Checksum Correct:   True 
    Package
        File Name:      Safari4.0.4SnowLeopard.dmg 
        Type:           dmg 
        Location:       
http://appldnld.apple.com.edgesuite.net/content.info.apple.com/Safari4/061-
7514.20091116.VgrPf/Safari4.0.4SnowLeopard.dmg 
        Checksum:       fb1755e32e9019e929474ef97ba4da219dee8b8f 
        Checksum Type:      sha1 
        Checksum Correct:   None 
        Cache Location:     Caches/InstaUp2DateCache/Safari4.0.4SnowLeopard.dmg
Traceback (most recent call last):
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 882, in <module>
    main()
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 872, in main
    thisController.parseFile(inputFilePath, topLevel=True)
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 234, in parseFile
    raise Exception('Error in config file: %s line number: %i\n%s' % (fileLocation, lineNumber, line)) # 
TODO: improve error handling
Exception: Error in config file: 
AddOns/InstaUp2Date/CatalogFiles/10.6_vanilla.catalog line 
number: 19
    Digital Camera Raw Compatibility Update 3.0 
http://support.apple.com/downloads/DL1001/en_US/RAWCameraUpdate3.dmsha1:99f04352
59
94dc91204204150a865f52e6707204


What version of InstaDMG are you running? What revision number (this should
be the second line of your package log)?


What OS are you running on (booted from)?


What OS are you installing?


Please provide any additional information below.

```

Original issue reported on code.google.com by `allister...@gtempaccount.com` on 20 Feb 2010 at 1:28

**Comment by GoogleCodeExporter** [comment]
```
Sorry I didn't fill the report out completely, didn't realize I can't edit the 
original issue report.

It is just line 19, of course.  A typo in the vanilla catalog file.  Fixed in 
attached file, love to be added as a 
contributor, please!

```

Original comment by `allister...@gtempaccount.com` on 20 Feb 2010 at 3:55

Attachments:
- [updated10.6_vanilla.catalog](https://storage.googleapis.com/google-code-attachments/instadmg/issue-33/comment-1/updated10.6_vanilla.catalog)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the bug report, as it happens I didn't see your post until after it 
was fixed (and Apple rolled another 
update). And I have added you in as a contributor, but please be very careful 
with that privilege.
```

Original comment by `kuehn.k...@gmail.com` on 27 Feb 2010 at 5:28
- Changed state: **Fixed**
