### ISSUE TITLE
instaUp2Date.py checksum error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#37]
```
What steps will reproduce the problem?
1. Run InstaUp2Date.py. Script will fail to find any file referenced in a
Catalog file to checksum it.


What is the expected output? What do you see instead?
Expected: Files should be checksummed and script should continue.

Output:
Looking for Mac OS X 10.6.3 v1.1 Combo Update
Traceback (most recent call last):
  File "./instaUp2Date.py", line 659, in <module>
    main()
  File "./instaUp2Date.py", line 642, in main
    thisController.parseFile(catalogFilePath)
  File "./instaUp2Date.py", line 200, in parseFile
    self.parseFile(
self.getCatalogFullPath(includeLineMatch.group("location")) )
  File "./instaUp2Date.py", line 224, in parseFile
    additionalCacheFolders = userSuppliedPKGFolderPath
  File "./instaUp2Date.py", line 406, in __init__
    cacheFilePath = self.checkCacheForItem(None, checksumType,
checksumValue, cacheFolders)
  File "./instaUp2Date.py", line 545, in checkCacheForItem
    if checksumValue == checksum.checksum(os.path.join(thisCacheFolder,
thisItemName), checksumType, tabsToPrefix=1)['checksum']:
  File "/Applications/instadmg/AddOns/InstaUp2Date/checksum.py", line 207,
in checksum
    readFile = open(thisTarget['sourceUrl'].path)
IOError: [Errno 2] No such file or directory:
'/../Caches/InstaUp2DateCache/MacOSXUpdCombo10.6.3v1.1
sha1-39d16279373906041a066f409b5f667e2bca77e2.dmg'

What version of InstaDMG are you running? What revision number (this should
be the second line of your package log)?
r281

What OS are you running on (booted from)?
10.6.3

What OS are you installing?
10.6

Please provide any additional information below.

Looks like bug is related to the path to the file that should be
checksummed. .dmg is appended to the sha1 checksum in error output:

 IOError: [Errno 2] No such file or directory:
'/../Caches/InstaUp2DateCache/MacOSXUpdCombo10.6.3v1.1
sha1-39d16279373906041a066f409b5f667e2bca77e2.dmg'

```

Original issue reported on code.google.com by `wgme...@gmail.com` on 27 Apr 2010 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
should be fixed in rev283. The problem was that when figuring out the absolute 
path to the InstaDMG folder I 
assumed that sys.argv[0] would be an absolute path (it always is the way I use 
it), but this is not always the case, 
so I have to generate a true absolute path.

The checksums belong in the cache file names, that is a speedup that came in 
with rev277 and is in the commit 
note for it.
```

Original comment by `kuehn.k...@gmail.com` on 29 Apr 2010 at 4:22
- Changed state: **Fixed**
