### ISSUE TITLE
354 instaup2date fails to run

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#54]
```
What steps will reproduce the problem?
1. svn checkout
2. attempt to run instaup2date with 10.6 vanilla catalog file and process flag
3.

What is the expected output? 
build to begin
What do you see instead?
exception(full text below)

Point-Admin-Allisters-MacBook-Pro:InstaUp2Date aru$ sudo ./instaUp2Date.py -p 
10.6_vanilla

Parsing the catalog files for 10.6_vanilla
    Mac OS X 10.6.4 Combo Update
    Remote Desktop Client 3.3.2
    iLife Support 9.0.4
    AirPort Base Station Update 2010-001 5.5.1
    Security Update 2010-005 for SnowLeopard
    Java For MacOS X 10.6 Update 2
    Snow Leopard Graphics Update 1.0
    Safari 5.0.2 Leopard/SnowLeopard
    iTunes 10
    Apple Magic Trackpad MultiTouch Update 1.0
    Digital Camera RAW Compatibility Update 3.3

Finding and validating the sources for 10.6_vanilla
    Mac OS X 10.6.4 Combo Update found by display name or checksum and verified in 3 seconds
    Remote Desktop Client 3.3.2 found by display name or checksum and verified in less than one second
    iLife Support 9.0.4 found by display name or checksum and verified in less than one second
    AirPort Base Station Update 2010-001 5.5.1 found by display name or checksum and verified in less than one second
    Security Update 2010-005 for SnowLeopard found by display name or checksum and verified in less than one second
    Java For MacOS X 10.6 Update 2 found by display name or checksum and verified in less than one second
    Snow Leopard Graphics Update 1.0 found by display name or checksum and verified in less than one second
    Safari 5.0.2 Leopard/SnowLeopard found by display name or checksum and verified in less than one second
    iTunes 10 found by display name or checksum and verified in less than one second
    Apple Magic Trackpad MultiTouch Update 1.0 found by display name or checksum and verified in less than one second
    Digital Camera RAW Compatibility Update 3.3 found by display name or checksum and verified in less than one second
Traceback (most recent call last):
  File "./instaUp2Date.py", line 531, in <module>
    main()
  File "./instaUp2Date.py", line 522, in main
    thisController.arrangeFolders(sectionFolders=sectionFolders)
  File "./instaUp2Date.py", line 301, in arrangeFolders
    os.symlink(thisItem.filePath, targetFilePath)
OSError: [Errno 2] No such file or directory


```

Original issue reported on code.google.com by `allister...@gtempaccount.com` on 8 Sep 2010 at 3:26

**Comment by GoogleCodeExporter** [comment]
```
Doh! 
Catalog error:
Safari 5.0.2 Leopard/SnowLeopard....

Please remove the forward slash, 10.5_vanilla would be broken in the same way.  
I thought I was going nuts when an old rev wasn't working with the new catalog 
file!

Allister
```

Original comment by `allister...@gtempaccount.com` on 8 Sep 2010 at 4:40
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kuehn.k...@gmail.com` on 19 Sep 2010 at 1:50
- Changed state: **Fixed**
