### ISSUE TITLE
r332 InstaUp2Date installaton of .app applications stopped working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#55]
```
In r331 I'm able to call applications that are straight .app files/folders 
which are not packaged in .pkg files.  that breaks in r332 and continues to 
HEAD.

Relevant Output: 

        cord-0.5.4 checksummed 128 items in less than one secondTraceback (most recent call last):
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 501, in <module>
    main()
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 483, in main
    thisController.parseFile(catalogFilePath)
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 242, in parseFile
    checksumString = packageLineMatch.group("fileChecksum"),
  File "/Users/jeff/instadmg/AddOns/InstaUp2Date/Resources/installerPackage.py", line 421, in __init__
    cacheFilePath = self.findItem(sourceLocation, self.checksumType, self.checksumValue, displayName=displayName, additionalSourceFolders=additionalSourceFolders, progressReporter=True)
  File "/Users/jeff/instadmg/AddOns/InstaUp2Date/Resources/installerPackage.py", line 281, in findItem
    raise FileNotFoundException('Could not locate the item: ' + nameOrLocation)
Resources.commonExceptions.FileNotFoundException: Could not locate the item: 
CoRD.app
```

Original issue reported on code.google.com by `jeffbea...@gmail.com` on 13 Sep 2010 at 2:29

**Comment by GoogleCodeExporter** [comment]
```
I don't know where I fixed this, but simple tests seem to be working fine. Make 
sure that your checksum is correct, there were some problems with the older 
code.
```

Original comment by `kuehn.k...@gmail.com` on 29 Sep 2010 at 9:59
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
You are correct,  I found an app that had a checksum that is now computing 
differently.  I'm building against HEAD this very moment.
```

Original comment by `jeffbea...@gmail.com` on 29 Sep 2010 at 12:45
