### ISSUE TITLE
importDisk.py will not now work with hardware RAID SAS drives

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#56]
```
This had been working fine all summer, suddenly I can no longer import a disk 
on my workstation which I use to build my lab's images. My machine has a 
hardware RAID card with SAS drives.

% svn checkout http://instadmg.googlecode.com/svn/trunk/ instadmg-read-only
% cd instadmg-read-only
% sudo ./AddOns/InstaUp2Date/importDisk.py --automatic --legacy
Traceback (most recent call last):
  File "./AddOns/InstaUp2Date/importDisk.py", line 215, in <module>
    main()
  File "./AddOns/InstaUp2Date/importDisk.py", line 76, in main
    for thisMountPoint in volumeManager.getMountedVolumes():
  File "/Users/jps3/Developer/instadmg-read-only/AddOns/InstaUp2Date/Resources/volumeManager.py", line 116, in getMountedVolumes
    thisVolumeInfo = volumeManager.getVolumeInfo(str(thisDisk))
  File "/Users/jps3/Developer/instadmg-read-only/AddOns/InstaUp2Date/Resources/volumeManager.py", line 97, in getVolumeInfo
    raise NotImplementedError('getVolumeInfo does not know how to deal with this volume:\n' + str(volumeProperties))
NotImplementedError: getVolumeInfo does not know how to deal with this volume:
{
    Bootable = 0;
    BusProtocol = SAS;
    CanBeMadeBootable = 0;
    CanBeMadeBootableRequiresDestroy = 0;
    Content = "GUID_partition_scheme";
    DeviceIdentifier = disk2;
    DeviceNode = "/dev/disk2";
    DeviceTreePath = "IODeviceTree:/PCI0@0/P0P9@9/P9P2@0/P2P3@0/PXS4@0";
    Ejectable = 0;
    FreeSpace = 0;
    GlobalPermissionsEnabled = 0;
    IOKitSize = 783691022336;
    Internal = 1;
    LowLevelFormatSupported = 0;
    MediaName = "APPLE RAID Card Media";
    MediaType = Generic;
    MountPoint = "";
    OS9DriversInstalled = 0;
    ParentWholeDisk = disk2;
    RAIDMaster = 0;
    RAIDSlice = 0;
    SMARTStatus = "Not Supported";
    SupportsGlobalPermissionsDisable = 0;
    SystemImage = 0;
    TotalSize = 783691022336;
    VolumeName = "";
    WholeDisk = 1;
    Writable = 1;
    WritableMedia = 1;
    WritableVolume = 0;
}


```

Original issue reported on code.google.com by `rustici...@gmail.com` on 13 Sep 2010 at 9:03

**Comment by GoogleCodeExporter** [comment]
```
I finally figured out that if I added 'SAS' and 'Fibre Channel Interface' to 
line 94 in volumeManager.py, and recompiled it, it runs! Oh, thank [insert 
diety of choice here]. This had me completely stressed out.
```

Original comment by `rustici...@gmail.com` on 13 Sep 2010 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
I am putting this in the newer versions, but don't have internal/fiber-channel 
RAIDs available. But for the record: you can always just provide importDisk.py 
the path to the volume you want to use and it will not use the guessing code.
```

Original comment by `kuehn.k...@gmail.com` on 18 Sep 2010 at 4:15
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kuehn.k...@gmail.com` on 10 Oct 2010 at 3:37
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
a) volumeManager.py: line 94 i added 'SCSI' to the array (i have a Sil3132 
Chipset)

b) volumeTools.py: line 61 i also added SCSI' to the array, and it corrected my 
importDisk.py issues

Cheers!!
```

Original comment by `jeremy.r...@gmail.com` on 23 Jul 2011 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
a) volumeManager.py: line 94 i added 'SCSI' to the array (i have a Sil3132 
Chipset)

b) volumeTools.py: line 61 i also added SCSI' to the array, and it corrected my 
importDisk.py issues

Cheers!!
```

Original comment by `jeremy.r...@gmail.com` on 23 Jul 2011 at 12:53
