### ISSUE TITLE
importDisk.py will not read Install DVD

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#62]
```
When I insert a 10.5 Install DVD into my PowerMAC the importDisk.py command 
will fail with the following error

sudo ./importDisk.py --automatic --legacy
Traceback (most recent call last):
  File "./importDisk.py", line 201, in <module>
    main()
  File "./importDisk.py", line 72, in main
    for thisMountPoint in volumeTools.getMountedVolumes():
  File "/Volumes/NetInstall Images/instadmg-105/AddOns/InstaUp2Date/Resources/volumeTools.py", line 82, in getMountedVolumes
    thisVolumeInfo = getDiskutilInfo(str(thisVolume))
  File "/Volumes/NetInstall Images/instadmg-105/AddOns/InstaUp2Date/Resources/volumeTools.py", line 64, in getDiskutilInfo
    raise NotImplementedError('getVolumeInfo does not know how to deal with this volume:\n' + str(volumeProperties))
NotImplementedError: getVolumeInfo does not know how to deal with this volume:
{
    BayName = "\"B (lower)\"";
    Bootable = 0;
    BusProtocol = ATA;
    CanBeMadeBootable = 0;
    CanBeMadeBootableRequiresDestroy = 0;
    Content = "Apple_partition_scheme";
    DeviceIdentifier = disk0;
    DeviceNode = disk0;
    DeviceTreePath = "sata/k2-sata@1/@0:0";
    Ejectable = 0;
    FreeSpace = 0;
    GlobalPermissionsEnabled = 0;
    Internal = 1;
    LowLevelFormatSupported = 0;
    MediaName = "SAMSUNG HD300LJ";
    MediaType = Generic;
    MountPoint = "";
    OS9DriversInstalled = 0;
    ParentWholeDisk = disk0;
    RAIDMaster = 0;
    RAIDSlice = 0;
    SMARTStatus = Verified;
    SupportsGlobalPermissionsDisable = 0;
    SystemImage = 0;
    TotalSize = 300069052416;
    VolumeName = "";
    WholeDisk = 1;
    Writable = 1;
}

```

Original issue reported on code.google.com by `paul.van...@gmail.com` on 6 Oct 2010 at 12:22

**Comment by GoogleCodeExporter** [comment]
```
This should work in version 384
```

Original comment by `kuehn.k...@gmail.com` on 10 Oct 2010 at 1:48
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Got the same error with rev 428 on Mac G5. 
volumeTools.py r412 doesn't have BusProtocal 'ATA' in line 61. Works after 
adding that.
```

Original comment by `psalo...@gmail.com` on 20 Sep 2011 at 10:22
