### ISSUE TITLE
can't run instaup2date under 10.5, with build 9G66

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#63]
```
What steps will reproduce the problem?
1. Use importdisk.py from 383
2. run instaup2date with cache and output folder options

What is the expected output? 
a successful run
What do you see instead?
all packages get checksummed, then when looking for OS disk, hits exception:

Finding the Installer disc for 1058_vanilla

Traceback (most recent call last):
  File "./instaUp2Date.py", line 665, in <module>
    main()
  File "./instaUp2Date.py", line 629, in main
    foundInstallerDiscs = findInstallerDisc.findInstallerDisc()
  File "/Volumes/SOLIDSTEEL/newestinstadmg383/AddOns/InstaUp2Date/Resources/findInstallerDisc.py", line 113, in findInstallerDisc
    if os.path.basename(candidateConainter.getStoragePath()) in legacyOSDiscNames:
AttributeError: 'NoneType' object has no attribute 'getStoragePath'

This is with the most current checkout from this evening, and with trying to 
rename the imported disk to legacy naming.

```

Original issue reported on code.google.com by `allister...@gtempaccount.com` on 10 Oct 2010 at 5:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `kuehn.k...@gmail.com` on 12 Oct 2010 at 5:49
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
```
Issue verified, with the addition that importDisk.py does not work beyond r367.

Moving previously generated build 10.5 9A581 to installer files in r383 gives 
the following:
Finding the Installer disc for 10.5_vanilla2
Traceback (most recent call last):
  File "./instaUp2Date.py", line 665, in <module>
    main()
  File "./instaUp2Date.py", line 627, in main
    foundInstallerDiscs = findInstallerDisc.findInstallerDisc(allowedBuilds=thisController.catalogFileSettings['Installer Disc Builds'])
  File "/Volumes/G6/InstaDMG/importDiskTesting/instadmgr383/AddOns/InstaUp2Date/Resources/findInstallerDisc.py", line 190, in findInstallerDisc
    raise commonExceptions.FileNotFoundException('Unable to find OS Installer disc in any provided folder: ' + str(searchItems))
Resources.commonExceptions.FileNotFoundException: Unable to find OS Installer 
disc in any provided folder: 
['/Volumes/G6/InstaDMG/importDiskTesting/instadmgr383/InstallerFiles/InstallerDi
scs', 
'/Volumes/G6/InstaDMG/importDiskTesting/instadmgr383/InstallerFiles/BaseOS']




```

Original comment by `drwe...@gmail.com` on 24 Oct 2010 at 7:49
