### ISSUE TITLE
InstaUp2Date functionality issue in 10.6.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#66]
```
What steps will reproduce the problem?
1. Modify 10.6_vanilla to comment out all except combo update
2. Run ./instaup2date.py with -p flag

What is the expected output? 
A successful run
What do you see instead?

Point-Admin-Allisters-MacBook-Pro:InstaUp2Date aru$ sudo ./instaUp2Date.py -p 
10.6_vanilla_testPassword:

Parsing the catalog files for 10.6_vanilla_test
    Mac OS X 10.6.4 Combo Update

Finding and validating the sources for 10.6_vanilla_test
    Mac OS X 10.6.4 Combo Update - found based on checksum and verified in 3 seconds

Finding the Installer disc for 10.6_vanilla_test
    Found Installer Disc:   /newestinstadmg388/InstallerFiles/BaseOS/Mac OS X Install DVD.dmg

Setting up for 10.6_vanilla_test
    Setting up InstaDMG folders

Running InstaDMG: /newestinstadmg388/instadmg.bash -f -I 
/newestinstadmg388/InstallerFiles/BaseOS/Mac OS X Install DVD.dmg -n Macintosh 
HD -m 10.6.4 Vanilla.dmg -K /private/tmp/idmg_temp.svJ3hZ/items-KooZLr -o 
/newestinstadmg388/OutputFiles

Traceback (most recent call last):
  File "./instaUp2Date.py", line 716, in <module>
    main()
  File "./instaUp2Date.py", line 705, in main
    thisController.runInstaDMG(scratchFolder=options.instadmgScratchFolder, outputFolder=options.instadmgOutputFolder)
  File "./instaUp2Date.py", line 471, in runInstaDMG
    if subprocess.call(instaDMGCommand) != 0:
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 444, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1106, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error


Note: modifying BasOS dmg name only makes error slightly different, as follows:
Finding the Installer disc for 10.6_vanilla_test
Traceback (most recent call last):
  File "./instaUp2Date.py", line 716, in <module>
    main()
  File "./instaUp2Date.py", line 680, in main
    foundInstallerDiscs = findInstallerDisc.findInstallerDisc()
  File "/newestinstadmg388/AddOns/InstaUp2Date/Resources/findInstallerDisc.py", line 190, in findInstallerDisc
    raise commonExceptions.FileNotFoundException('Unable to find OS Installer disc in any provided folder: ' + str(searchItems))
Resources.commonExceptions.FileNotFoundException: Unable to find OS Installer 
disc in any provided folder: ['/newestinstadmg388/InstallerFiles/BaseOS']


```

Original issue reported on code.google.com by `allister...@gtempaccount.com` on 20 Oct 2010 at 1:00

**Comment by GoogleCodeExporter** [comment]
```
Turn out there must be some legacy tomfoolery, creating a new directory instead 
of 'svn update'ing at least allows a functional run.  Not sure if updating in 
this matter should be considered a 'warranty-able' feature, turning down 
priority and adjusting type accordingly 
```

Original comment by `allister...@gtempaccount.com` on 20 Oct 2010 at 1:15
- Added labels: **Priority-Low**, **Type-Other**
- Removed labels: **Priority-High**, **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kuehn.k...@gmail.com` on 20 Oct 2010 at 1:30

**Comment by GoogleCodeExporter** [comment]
Original comment by `kuehn.k...@gmail.com` on 21 Oct 2010 at 7:37
- Changed state: **New**
