### ISSUE TITLE
can't run importDisk in 10.5.8 after r367

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#70]
```
What steps will reproduce the problem?
1. checkout r367 on system running 10.5.8
2. sudo ./importDisk.py --automatic
3. Image "MacOS X Client 10.5 9A581.dmg" created in 1 hour 2 minutes 36 seconds

4. checkout r385 on system running 10.5.8
5. sudo ./importDisk.py --automatic
6. importDisk.py: error: Error: There were no possible disks to image

7. checkout r389 on system running 10.5.8
8. sudo ./importDisk.py --automatic
9. importDisk.py: error: Error: There were no possible disks to image


What is the expected output? What do you see instead?
Expected: Log message: Image "MacOS X Client 10.5 9A581.dmg" created in 1 hour 
2 minutes 36 seconds. Confirm MacOS X Client 10.5 9A581.dmg created in 
Installer Disks.

Actual: importDisk.py: error: Error: There were no possible disks to image

What version of InstaDMG are you running? What revision number (this should
be the second line of your package log)?
tested on cahnges if importDisk.py r363, r367 (successful), r385, r389

What OS are you running on (booted from)?
10.5.8

What OS are you installing?
10.5_vanilla

Please provide any additional information below.
importDisk.py Issues in 10.5.8
All testing with 10.5 build 9A581

r363
G4-boot-10-5-8:InstaUp2Date itdeptadmin$ cd 
/Volumes/G6/InstaDMG/importDiskTesting/instadmgr363/AddOns/InstaUp2Date 
G4-boot-10-5-8:InstaUp2Date itdeptadmin$ sudo ./importDisk.py --automatic
/Volumes/G6/InstaDMG/importDiskTesting/instadmgr363/AddOns/InstaUp2Date/Resource
s/containerTypes/container.py:45: Warning: 'with' will become a reserved 
keyword in Python 2.6
Traceback (most recent call last):
  File "./importDisk.py", line 10, in <module>
    import Resources.containerController    as containerController
  File "/Volumes/G6/InstaDMG/importDiskTesting/instadmgr363/AddOns/InstaUp2Date/Resources/containerController.py", line 3, in <module>
    from containerTypes     import *
  File "/Volumes/G6/InstaDMG/importDiskTesting/instadmgr363/AddOns/InstaUp2Date/Resources/containerTypes/container.py", line 45
    with warnings.catch_warnings():
                ^
SyntaxError: invalid syntax


r367
G4-boot-10-5-8:InstaUp2Date itdeptadmin$ cd 
/Volumes/G6/InstaDMG/importDiskTesting/instadmgr367/AddOns/InstaUp2Date 
G4-boot-10-5-8:InstaUp2Date itdeptadmin$ sudo ./importDisk.py --automatic
Image "MacOS X Client 10.5 9A581.dmg" created in 1 hour 2 minutes 36 seconds


r385
G4-boot-10-5-8:InstaUp2Date itdeptadmin$ cd 
/Volumes/G6/InstaDMG/importDiskTesting/instadmgr385/AddOns/InstaUp2Date 
G4-boot-10-5-8:InstaUp2Date itdeptadmin$ sudo ./importDisk.py --automatic
Password:
Usage: importDisk.py [options]

importDisk.py: error: Error: There were no possible disks to image


r389
G4-boot-10-5-8:InstaUp2Date itdeptadmin$ cd 
/Volumes/G6/InstaDMG/importDiskTesting/instadmgr389/AddOns/InstaUp2Date 
G4-boot-10-5-8:InstaUp2Date itdeptadmin$ ./importDisk.py --automatic
Usage: importDisk.py [options]

importDisk.py: error: Error: There were no possible disks to image


```

Original issue reported on code.google.com by `drwe...@gmail.com` on 24 Oct 2010 at 6:10

**Comment by GoogleCodeExporter** [comment]
```
Fixed in rev391. Was a problem with 10.5 using a different key name for volume 
write-ability in 10.5 and 10.6.
```

Original comment by `kuehn.k...@gmail.com` on 24 Oct 2010 at 9:17
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Fix verified.

Thanks Karl
```

Original comment by `drwe...@gmail.com` on 24 Oct 2010 at 11:09
