### ISSUE TITLE
r391 Apple Retail disks 10.5.4 Build 9E25 & 10.5.6 Build 9G66 missing from 10.5_vanilla, instaup2date.py fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#71]
```
What steps will reproduce the problem?
1. sudo ./importDisk.py --automatic
2. sudo sudo ./instaUp2Date.py 10.5_vanilla -p --instadmg-scratch-folder 
/Volumes/G4-Data

What is the expected output? What do you see instead?
Expected: 
normal run of instaup2date

Actual:
Finding the Installer disc for 10.5_vanilla
Traceback (most recent call last):
  File "./instaUp2Date.py", line 716, in <module>
    main()
  File "./instaUp2Date.py", line 678, in main
    foundInstallerDiscs = findInstallerDisc.findInstallerDisc(allowedBuilds=thisController.installerDiscBuilds)
  File "/Volumes/G6/InstaDMG/importDiskTesting/instadmgr391/AddOns/InstaUp2Date/Resources/findInstallerDisc.py", line 191, in findInstallerDisc
    raise commonExceptions.FileNotFoundException('Unable to find OS Installer disc in any provided folder: ' + str(searchItems))
Resources.commonExceptions.FileNotFoundException: Unable to find OS Installer 
disc in any provided folder: 
['/Volumes/G6/InstaDMG/importDiskTesting/instadmgr391/InstallerFiles/InstallerDi
scs', 
'/Volumes/G6/InstaDMG/importDiskTesting/instadmgr391/InstallerFiles/BaseOS']

What version of InstaDMG are you running? What revision number (this should
be the second line of your package log)?
r391

What OS are you running on (booted from)?
10.5.8

What OS are you installing?
10.5.8

Please provide any additional information below.
http://support.apple.com/kb/ht1633

Fix:
Add 9E25 & 9G66 to
Installer Disc Builds:  9A581, 9B18, 9C31, 9D34, 9E17, 9F33, 9G55, 9J61, 9L30, 
9E25, 9G66

Tested with 10.5.4 9E25
Require a copy of 10.5.6 9G66 to test.
```

Original issue reported on code.google.com by `drwe...@gmail.com` on 24 Oct 2010 at 11:08

**Comment by GoogleCodeExporter** [comment]
```
This should also fix issue 62: can't run instaup2date under 10.5, with build 
9G66 
```

Original comment by `drwe...@gmail.com` on 24 Oct 2010 at 11:43

**Comment by GoogleCodeExporter** [comment]
```
Thanks!  Fixing now.
```

Original comment by `allister...@gtempaccount.com` on 18 Nov 2010 at 3:32
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
I said fixing 'now', didn't I... Sorry about that, will add 9E25 with the next 
commit, thanks for references as well
```

Original comment by `allister...@gtempaccount.com` on 20 May 2011 at 2:19
