### ISSUE TITLE
findInstallerDisc.py does not OS install disc any longer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#72]
```
What steps will reproduce the problem?
1. sudo ./instadmg/AddOns/InstaUp2Date/instaUp2Date.py 10.5_vanilla --process


What is the expected output? What do you see instead?

Expected: 

findInstallerDisc.py will find the BaseOS and continue. 

Actual: 

Finding the Installer disc for 10.5_vanilla
Traceback (most recent call last):
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 716, in <module>
    main()
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 678, in main
    foundInstallerDiscs = findInstallerDisc.findInstallerDisc(allowedBuilds=thisController.installerDiscBuilds)
  File "/Users/ladmin/Desktop/image_creation/10.5client/instadmg/AddOns/InstaUp2Date/Resources/findInstallerDisc.py", line 191, in findInstallerDisc
    raise commonExceptions.FileNotFoundException('Unable to find OS Installer disc in any provided folder: ' + str(searchItems))
Resources.commonExceptions.FileNotFoundException: Unable to find OS Installer 
disc in any provided folder: 
['/Users/ladmin/Desktop/image_creation/10.5client/instadmg/InstallerFiles/Instal
lerDiscs', 
'/Users/ladmin/Desktop/image_creation/10.5client/instadmg/InstallerFiles/BaseOS'
]


What version of InstaDMG are you running? What revision number (this should
be the second line of your package log)?

revision 394

What OS are you running on (booted from)?

10.6.4 Server

What OS are you installing?

10.5 client and 10.6 client - neither of them can find the install disc


```

Original issue reported on code.google.com by `fosh...@gmail.com` on 30 Oct 2010 at 5:24

**Comment by GoogleCodeExporter** [comment]
```
As a new InstaDMG user, I think it would be helpful for InstaUp2Date to output 
a slightly more helpful message here rather than the current exception trace. 
For instance:

Unable to find OS Installer disc with any of the following build numbers:
    10A432
    10B504
    10C540
    10D573
    10D575
    10F569
...in any of the following folders:
    /Users/ladmin/Desktop/image_creation/10.5client/instadmg/InstallerFiles/InstallerDiscs
    /Users/ladmin/Desktop/image_creation/10.5client/instadmg/InstallerFiles/BaseOS
```

Original comment by `joe.woll...@gmail.com` on 17 Jun 2011 at 2:57
