### ISSUE TITLE
svn 413 with vanilla 10.6 can't find imported 10.6.3 retail.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#79]
```
What steps will reproduce the problem?
1. svn update to 413
2. Insert 10.6.3 retail DVD in drive.
3. AddOns/InstaUp2Date/importDisk.py and answer yes, yes.
4. MD5 (MacOS X Client 10.6.3 10D575.dmg) = f65668df2894b3c97ce086ebcb37b103
5. sudo AddOns/InstaUp2Date/instaUp2Date.py -p 
AddOns/InstaUp2Date/CatalogFiles/10.6_vanilla.catalog

What is the expected output? What do you see instead?

Parsing the catalog files for 10.6_vanilla
    Mac OS X 10.6.6 Combo Update
    iTunes10.1.1
    Safari 5.0.3
    Java For MacOSX 10.6 Update 3
    AirPort Utility 5.5.2
    Remote Desktop Client 3.4

Finding and validating the sources for 10.6_vanilla
    Mac OS X 10.6.6 Combo Update - found based on checksum and verified in 4 seconds
    iTunes10.1.1 - found based on checksum and verified in less than one second
    Safari 5.0.3 - found based on checksum and verified in less than one second
    Java For MacOSX 10.6 Update 3 - found based on checksum and verified in less than one second
    AirPort Utility 5.5.2 - found based on checksum and verified in less than one second
    Remote Desktop Client 3.4 - found based on checksum and verified in less than one second

Finding the Installer disc for 10.6_vanilla
Traceback (most recent call last):
  File "AddOns/InstaUp2Date/instaUp2Date.py", line 716, in <module>
    main()
  File "AddOns/InstaUp2Date/instaUp2Date.py", line 678, in main
    foundInstallerDiscs = findInstallerDisc.findInstallerDisc(allowedBuilds=thisController.installerDiscBuilds)
  File "/Users/Shared/DAFGU/instadmg/AddOns/InstaUp2Date/Resources/findInstallerDisc.py", line 201, in findInstallerDisc
    raise commonExceptions.FileNotFoundException('Unable to find OS Installer disc in any provided folder: %s%s' % (str(searchItems), folderString))
Resources.commonExceptions.FileNotFoundException: Unable to find OS Installer 
disc in any provided folder: 
['/Users/Shared/DAFGU/instadmg/InstallerFiles/InstallerDiscs', 
'/Users/Shared/DAFGU/instadmg/InstallerFiles/BaseOS'] (['.svn', 'MacOS X Client 
10.6.3 10D575.dmg'], ['.svn'])


What version of InstaDMG are you running? What revision number (this should
be the second line of your package log)?
413

What OS are you running on (booted from)?
10.6.6

What OS are you installing?
10.6.3 with 10.6.6 Combo

Please provide any additional information below.

```

Original issue reported on code.google.com by `MagerV...@gmail.com` on 21 Jan 2011 at 10:25

**Comment by GoogleCodeExporter** [comment]
```
Ejecting a mounted 10.6 Server install image helped.
```

Original comment by `MagerV...@gmail.com` on 21 Jan 2011 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Hey MV, 
I know this is a issue for myself and others recently, as you mentioned on the 
applicable thread on afp548.  It must be between findInstallerDisc.py and the 
disk arbitration framework, I'll see if I can replicate the problem and then 
work on a test that reproduces it, before I then attempt any code changes that 
would make the test pass.  I'm calling this started even though I'm a long ways 
down the road from making progress.  Thanks
```

Original comment by `allister...@gtempaccount.com` on 21 Jan 2011 at 2:15
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I can confirm the same error if i have any kind of mounted disks on the 
machine. After ejecting all disks I can run the script again with success.
```

Original comment by `maxvaill...@gmail.com` on 14 Mar 2011 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
I'm wondering if this has fallen by the wayside. I'm on 10.6.8 trying to build 
from Mac OS X SERVER 10.6.3, and I'm getting the same error that it can't find 
install media. Disc image is named "Mac OS X Server 10.6.3 10D575.dmg" and I've 
confirmed that 10D575 is in my allowed media list for the catalog. Am I missing 
something glaringly obvious? :)
```

Original comment by `jeremy.k...@gmail.com` on 13 Nov 2011 at 10:14

**Comment by GoogleCodeExporter** [comment]
```
Try without a space between MacOS in the filename.
```

Original comment by `MagerV...@gmail.com` on 17 Nov 2011 at 7:19

**Comment by GoogleCodeExporter** [comment]
```
Apparently Mac OS X Server isn't supported before Lion. Anybody know what the 
actual issues are that cause this to not work? I'd love to take a crack at 
getting around them.
```

Original comment by `jeremy.k...@gmail.com` on 17 Nov 2011 at 8:15

**Comment by GoogleCodeExporter** [comment]
```
The main issue is that the 'Server installer needs to ask questions during the 
install, and we have no way of answering them. Turns out that there is an 
answer file format that if the installer can find it will skip those questions, 
but I did not know that when I could still work on InstaDMG. With that file on 
the root of a visible volume (probably even a mounted image) the install might 
work in InstaDMG with no further changes. But I don't know that.

The second issue was more a lack of interest on my part. I had (and still have) 
no real need for images of 'Server, and no personal license for 'Server, so I 
spent no time on trying to get it to work.
```

Original comment by `kuehn.k...@gmail.com` on 17 Nov 2011 at 8:32

**Comment by GoogleCodeExporter** [comment]
```
This is getting off topic, but I'd like to point out that System Image Utility 
can build NetRestore images from server media. Together with Auto Server Setup 
files you get a fully automated server deploy.
```

Original comment by `MagerV...@gmail.com` on 17 Nov 2011 at 8:37
