### ISSUE TITLE
r376 added dependency in instaUp2Date on svn $Revision$ that breaks when run from HgSubversion clones

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#80]
```
What steps will reproduce the problem?
1. Install current versions of Mercurial and HgSubversion, along with 
dependencies for each.
2. Clone the InstaDMG trunk locally, using Hg.
3. Set up InstaUp2Date catalogs and source images to your liking.
4. Attempt to run InstaUp2Date.

What is the expected output? What do you see instead?

InstaUp2Date should run without error. The last revision I used, which did not 
feature the $Revision$ marker, did -- even when cloned with Mercurial and 
HgSubversion.

InstaUp2Date from r392, however, fails immediately with this exception:

Traceback (most recent call last):
  File "./instaUp2Date.py", line 12, in <module>
    import Resources.pathHelpers            as pathHelpers
  File "/Users/powercctrip/Downloads/instadmg-ro/AddOns/InstaUp2Date/Resources/pathHelpers.py", line 3, in <module>
    __version__ = "$Revision$".split()[1]
IndexError: list index out of range

What version of InstaDMG are you running? What revision number (this should
be the second line of your package log)?

InstaDMG is updated from SVN trunk as of 1/21/2011. InstaUp2Date.py corresponds 
to r392, where it was last checked in.

What OS are you running on (booted from)?

Mac OS X 10.6.6.

What OS are you installing?

Mac OS X 10.6.6.

Please provide any additional information below.

When cloning the SVN repository for InstaDMG, $Revision$ is left in the source 
code of instaUp2Date.py. Not being an SVN user, I suspect that SVN would have 
inserted a revision at this marker.
```

Original issue reported on code.google.com by `jaha...@gmail.com` on 21 Jan 2011 at 7:31

**Comment by GoogleCodeExporter** [comment]
```
I can confirm the same issue when cloning via git svn clone.
```

Original comment by `t...@synthist.net` on 11 Feb 2011 at 9:02

**Comment by GoogleCodeExporter** [comment]
```
File bugs with the hg and git projects. Subversion clients (and hg and git are 
functioning as Subversion clients in these instances) are responsible for 
expanding keywords, and they're clearly not doing that, so that's their bug.
```

Original comment by `ryandesi...@gmail.com` on 13 Mar 2011 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
Should be fixed as of ~r452 by manually changing those values to be static
```

Original comment by `a...@aru-b.com` on 15 Jun 2012 at 3:34
- Changed state: **Fixed**
