### ISSUE TITLE
Collect a fully patched dmg 10.6.6 failes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#82]
```
What steps will reproduce the problem?
1.
sudo ./instadmg/AddOns/InstaUp2Date/instaUp2Date.py 10.6_vanilla --process
2.
3.

What is the expected output? What do you see instead?
Expected output is a fully patched 10.6.6 Vanilla.dmg

But get the following Error:
Traceback (most recent call last):
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 716, in <module>
    main()
  File "./instadmg/AddOns/InstaUp2Date/instaUp2Date.py", line 678, in main
    foundInstallerDiscs = findInstallerDisc.findInstallerDisc(allowedBuilds=thisController.installerDiscBuilds)
  File "/Users/belmac42/instadmg/AddOns/InstaUp2Date/Resources/findInstallerDisc.py", line 201, in findInstallerDisc
    raise commonExceptions.FileNotFoundException('Unable to find OS Installer disc in any provided folder: %s%s' % (str(searchItems), folderString))
Resources.commonExceptions.FileNotFoundException: Unable to find OS Installer 
disc in any provided folder: 
['/Users/belmac42/instadmg/InstallerFiles/InstallerDiscs', 
'/Users/belmac42/instadmg/InstallerFiles/BaseOS'] (['.svn'], ['.svn', 'Mac OS X 
Install DVD.dmg'])


What version of InstaDMG are you running? What revision number (this should
be the second line of your package log)?
Version 1.6rc1

What OS are you running on (booted from)?
10.6.6 client mac


What OS are you installing?
10.6.6 client

Please provide any additional information below.

```

Original issue reported on code.google.com by `jan.bult...@skynet.be` on 10 Feb 2011 at 2:08

**Comment by GoogleCodeExporter** [comment]
```
Is the dmg mounted? If it is, eject it before running InstaUp2Date (see issue 
79).
```

Original comment by `MagerV...@gmail.com` on 10 Feb 2011 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
I was able to get it going by commenting the line:
#Installer Disc build = 10A432, 10B504......

Is it mandatory to use a retail disc to build the base OS disc image?

I used the grey disc which came with the mac, this could have been the problem?

tx,jan
```

Original comment by `jan.bult...@skynet.be` on 10 Feb 2011 at 8:11

**Comment by GoogleCodeExporter** [comment]
```
Hey Jan,
No, it's not mandatory, just highly recommended, as therefore your image will 
likely contain drivers for all shipping systems and not just the one(s) that 
the disc came with.  I'm closing this issue as it is an intended design 
decision and explained in the docs.  Even though 10.6.6 is out and supports the 
most recent models(MacBookAirs), you can modify the tool to your needs as new 
models eclipse the most recent combo update in the future, as mentioned in the 
InstaUp2Date wiki.  Thanks, Allister
```

Original comment by `allister...@gtempaccount.com` on 15 Feb 2011 at 1:49
- Changed state: **Done**
- Added labels: **Type-Other**
- Removed labels: **Type-Defect**
