### ISSUE TITLE
Unable to locate installESD.dmg

### ISSUE THREAD

**Issue by GoogleCodeExporter** [n8felton/instadmg#96]
```
What steps will reproduce the problem?
1.itsadmin$ sudo ./instaUp2Date.py -p 10.7_vanilla


What is the expected output? What do you see instead?
I would expect for it to find the InstallESD.dmg but instead says it cant find 
it

Finding the Installer disc for 10.7_vanilla
Traceback (most recent call last):
  File "./instaUp2Date.py", line 716, in <module>
    main()
  File "./instaUp2Date.py", line 678, in main
    foundInstallerDiscs = findInstallerDisc.findInstallerDisc(allowedBuilds=thisController.installerDiscBuilds)
  File "/Users/itsadmin/Desktop/InstaDMG/AddOns/InstaUp2Date/Resources/findInstallerDisc.py", line 201, in findInstallerDisc
Resources.commonExceptions.FileNotFoundException: Unable to find OS Installer 
disc in any provided folder: 
['/Volumes/Data/InstaDMG/InstallerFiles/InstallerDiscs', 
'/Volumes/Data/InstaDMG/InstallerFiles/BaseOS'] (['.DS_Store', 
'InstallESD.dmg'], ['InstallESD.dmg'])

I have the InstallESD.dmg copied into the following locations 
/InstallerFiles/BaseOS
/InstallerFiles/nstallerDiscs
/InstaDMG/InstallerFiles/BaseOS
/InstaDMG/InstallerFiles/InstallerDiscs


What version of InstaDMG are you running? What revision number (this should
be the second line of your package log)?
svn update returns '.'
it was downloaded yesterday so it is the latest revision


What OS are you running on (booted from)?
10.6.8


What OS are you installing?
10.7.2

Please provide any additional information below.
The installESD.dmg file was obtained from the recovery partition on a mac mini. 
I have updated the 10.7 catalog to install that builds disc number

Installer Disc Builds:  11A511, 11B26, 11B2118, 11C74

The machine i am running instaDMG from only has 1gb of ram and can not actually 
install 10.7, but i would not have imagined that this would prevent instaDMG 
from compiling an image

```

Original issue reported on code.google.com by `nicoipho...@gmail.com` on 14 Oct 2011 at 1:29

**Comment by GoogleCodeExporter** [comment]
```
The first big problem is that you should not be creating a 10.7 image from 
10.6.8. Always create images from at least the target OS. Latter can often 
work, but there are no good bets on earlier OSs being able to install later OSs.

The debug output shows that it is finding the InstallerESD files, but because 
it does not have the versions that it is looking for (11A511, 11B26, 11B2118, 
11C74) it will not work. Presumably you have something that is not on that list.

You did not give the version of InstaDMG that you are running. There are 
multiple ways of getting it, so this is an important question. "svn update" is 
not going to return things if you downloaded from a zip.
```

Original comment by `kuehn.k...@gmail.com` on 14 Oct 2011 at 2:26
- Changed state: **Invalid**
